### ISSUE TITLE
Edit reservations (calendar)

### ISSUE THREAD

**Issue by LLaudrup** [laudrup/ebbamaala#8] opened 2021-09-07 16:52 UTC
It would be great if it was possible to edit your own reservations in the calendar on the site. Thanks 🙏

**Comment by laudrup** [comment] 2021-11-05 13:36
This has been addressed in a4582171b9897d86a8e2511b487862e8e36c244a.

As it is now, instead of just showing the booking, if the user owns the booking and/or is a member of the admin group the booking will be editable just as if it was a new booking.

It is live now on https://ebbamåla.se.

Let me know if this works as intended and I can close this issue.

Thanks.

**Closed** 2021-11-06 15:34 UTC
